`define LOW_RESOLUTION_FONT_ADDRESS     16'h0000
`define LOW_RESOLUTION_FONT_LENGTH      8'h50
`define HIGH_RESOLUTION_FONT_ADDRESS    16'h0050
`define HIGH_RESOLUTION_FONT_LENGTH     8'ha0
`define FLAGS_ADDRESS                   16'h00f0
`define FLAGS_LENGTH                    8'h10
`define TITLE_ADDRESS                   16'h0100
`define TITLE_LENGTH                    8'h20
`define AUTHOR_ADDRESS                  16'h0120
`define AUTHOR_LENGTH                   8'h10
`define DESCRIPTION_ADDRESS             16'h0130
`define DESCRIPTION_LENGTH              8'h50
`define QUIRKS_ADDRESS                  16'h0180
`define QUIRKS_LENGTH                   8'h08
`define KEYMAP_ADDRESS                  16'h0188
`define KEYMAP_LENGTH                   8'h08
`define PALETTE_ADDRESS                 16'h0190
`define PALETTE_LENGTH                  8'h02
`define INSTRUCTIONS_PER_FRAME_ADDRESS  16'h0192
`define INSTRUCTIONS_PER_FRAME_LENGTH   8'h02
`define LAST_PAGE_ADDRESS               16'h194
`define LAST_PAGE_LENGTH                8'h01
